In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('data/all leads 20240116.csv')

In [45]:
phone_numbers = ['phone_1', 'phone_2', 'phone_3',]
dnc_identifiers = ['phone_1_do_not_call', 'phone_2_do_not_call', 'phone_3_do_not_call']
id_vars = ['associated_property_address_full', 'first_name', 'last_name','middle_initial']

In [49]:
# remove phone numbers that are marked DO NOT CALL
df['phone_2'] = np.where(df['phone_2_do_not_call'] == 'DO NOT CALL', np.nan, df['phone_2'])
df['phone_3'] = np.where(df['phone_3_do_not_call'] == 'DO NOT CALL', np.nan, df['phone_3'])
df['phone_1'] = np.where(df['phone_1_do_not_call'] == 'DO NOT CALL', np.nan, df['phone_1'])

In [58]:
# drop rows where all three phone numbers are missing
out = df.loc[df[phone_numbers].dropna(axis=0, how='all').index]

In [61]:
out.to_csv('data/cleaned_list.csv')

In [59]:
out.head()

,contact_id,lead_id,associated_property_id,associated_property_address_full,associated_property_address_line_1,associated_property_address_line_2,associated_property_address_city,associated_property_address_state,associated_property_address_zipcode,first_name,...,phone_2_usage_2_months,phone_2_usage_12_months,phone_3,phone_3_do_not_call,phone_3_activity_status_code,phone_3_owner,phone_3_prepaid_indicator,phone_3_type,phone_3_usage_2_months,phone_3_usage_12_months
2,1.506020e+11,45565210,2151185782,"317 Hewitt St, Neenah, Wi 54956",317 Hewitt St,NaN,Neenah,WI,54956,TINA,...,No data available or no usage in the last 2 mo...,Minimal Usage,NaN,NaN,NaN,NaN,NaN,Landline,No data available or no usage in the last 2 mo...,No data available or no usage in the last 2 mo...
3,1.501080e+12,45565232,2151185788,"303 Hewitt St, Neenah, Wi 54956",303 Hewitt St,NaN,Neenah,WI,54956,KAYLA,...,No data available or no usage in the last 2 mo...,Minimal Usage,NaN,DO NOT CALL,A6,AT&T Mobility,PREPAID,Wireless,Minimal Usage,Light Usage
7,1.504130e+11,45565393,2151203904,"1109 E Forest Ave, Neenah, Wi 54956",1109 E Forest Ave,NaN,Neenah,WI,54956,THOMAS,...,Minimal Usage,Minimal Usage,NaN,DO NOT CALL,A7,US Cellular,PREPAID,Wireless,Light Usage,Heavy Usage
8,1.509630e+11,45565393,2151203904,"1109 E Forest Ave, Neenah, Wi 54956",1109 E Forest Ave,NaN,Neenah,WI,54956,VIVAN,...,Moderate Usage,Heavy Usage,9.204867e+09,NaN,I4,Time Warner Cable,PREPAID,Landline,Minimal Usage,Light Usage
9,1.504230e+11,45567956,2151202797,"402 7th St, Neenah, Wi 54956",402 7th St,NaN,Neenah,WI,54956,MARTIN,...,No data available or no usage in the last 2 mo...,No data available or no usage in the last 2 mo...,NaN,NaN,NaN,NaN,NaN,Landline,No data available or no usage in the last 2 mo...,No data available or no usage in the last 2 mo...